In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df = df.iloc[:,2:]

In [5]:
df.sample(5)

     Age  EstimatedSalary  Purchased
71    24            27000          0
393   60            42000          1
3     27            57000          0
314   39            79000          0
285   37            93000          1

### Train Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased',axis=1),
                                                    df['Purchased'],test_size=0.3,
                                                    random_state = 10)

In [13]:
type(X_train)

pandas.core.frame.DataFrame

In [14]:
X_test.sample(5)

     Age  EstimatedSalary
92    26            15000
295   36            63000
66    24            19000
357   41            72000
138   28            59000

### Standard Scaler

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)  # fit the scaler to train set, so that it can learn the parameters

# transform train and test data using standard scaler
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
X_train_scaled

array([[ 1.10639192, -0.98126643],
       [ 0.91259164, -1.44163648],
       [ 1.20329206, -0.98126643],
       [-0.25021   ,  0.19843182],
       [-0.63781054, -0.34825761],
       [ 0.42809096, -0.17561884],
       [ 0.5249911 ,  1.69463449],
       [ 0.71879137, -1.38409022],
       [-0.83161082, -0.77985453],
       [ 1.97849315,  0.71634813],
       [ 0.33119082, -0.54966951],
       [-0.25021   ,  0.77389439],
       [-0.83161082,  0.14088557],
       [ 0.23429069, -0.37703074],
       [ 0.33119082, -1.1539052 ],
       [ 1.88159301,  0.11211244],
       [ 0.71879137, -1.09635894],
       [-0.44401027, -1.21145146],
       [-0.25021   ,  2.21255079],
       [-0.25021   , -0.26193823],
       [ 0.13739055,  0.08333931],
       [ 1.10639192,  0.54370936],
       [ 1.00949178, -1.1539052 ],
       [ 1.30019219,  2.18377766],
       [-1.02541109,  0.74512126],
       [ 1.5908926 ,  0.97530628],
       [-0.25021   , -1.24022458],
       [ 0.33119082,  0.05456618],
       [ 1.00949178, -1.18267833],
       [ 0.81569151,  0.74512126],
       [ 0.23429069, -0.26193823],
       [-1.12231123,  0.45738998],
       [-1.02541109, -0.34825761],
       [-0.34711013,  0.05456618],
       [ 1.97849315, -0.92372017],
       [ 0.91259164, -0.54966951],
       [ 1.68779274,  1.57954197],
       [-1.80061218, -1.41286335],
       [ 1.30019219, -1.3553171 ],
       [ 1.39709233,  2.29887018],
       [-1.02541109, -1.44163648],
       [ 0.91259164, -0.60721576],
       [ 0.81569151,  1.34935695],
       [-1.12231123, -1.01003956],
       [-1.80061218, -1.29777084],
       [-1.12231123, -1.09635894],
       [-0.63781054,  0.54370936],
       [ 1.20329206,  0.51493623],
       [-1.50991177, -1.49918274],
       [-0.25021   ,  0.02579305],
       [-0.34711013,  1.20549131],
       [ 0.33119082,  0.25597808],
       [ 0.13739055,  0.02579305],
       [ 0.23429069,  0.14088557],
       [-0.83161082, -0.26193823],
       [-1.12231123,  0.05456618],
       [-0.05640972,  1.92481951],
       [-0.44401027, -0.29071136],
       [-0.05640972, -0.52089638],
       [-0.92851095, -1.09635894],
       [-0.73471068,  0.4861631 ],
       [-0.15330986, -0.52089638],
       [ 1.00949178,  0.11211244],
       [-1.50991177, -0.20439197],
       [-0.25021   ,  0.05456618],
       [-1.80061218, -1.47040961],
       [-1.3161115 , -1.09635894],
       [-0.25021   , -0.37703074],
       [ 0.81569151,  0.11211244],
       [-0.15330986,  1.37813008],
       [-1.3161115 , -0.434577  ],
       [ 0.91259164,  1.06162567],
       [ 0.42809096,  2.27009705],
       [-0.15330986,  1.57954197],
       [-0.25021   ,  0.51493623],
       [-0.63781054, -1.58550212],
       [ 0.13739055,  1.83850013],
       [-1.02541109,  0.54370936],
       [-0.54091041,  1.43567633],
       [-1.12231123,  0.39984372],
       [-0.25021   ,  0.25597808],
       [ 0.42809096,  0.08333931],
       [ 1.5908926 ,  1.0903988 ],
       [ 0.42809096, -0.00298007],
       [ 0.23429069,  0.05456618],
       [-1.70371205, -0.98126643],
       [-1.70371205,  0.34229746],
       [-1.3161115 , -0.434577  ],
       [-0.05640972, -0.00298007],
       [-0.54091041,  0.86021377],
       [-1.21921136,  0.25597808],
       [-0.25021   ,  0.05456618],
       [-0.05640972, -1.06758582],
       [ 0.13739055,  0.14088557],
       [ 0.04049041, -0.434577  ],
       [-0.25021   , -0.66476202],
       [-0.73471068, -0.2331651 ],
       [ 1.97849315,  2.12623141],
       [ 0.23429069,  0.02579305],
       [-0.25021   ,  0.14088557],
       [ 0.04049041,  0.02579305],
       [ 0.5249911 ,  1.809727  ],
       [-1.80061218, -0.00298007],
       [-1.12231123, -0.77985453],
       [-0.73471068,  1.06162567],
       [ 0.23429069, -0.37703074],
       [ 0.04049041,  1.23426444],
       [-0.25021   ,  0.14088557],
       [-0.15330986,  0.14088557],
       [-1.12231123,  0.28475121],
       [ 0.42809096,  0.97530628],
       [-0.73471068,  0.25597808],
       [ 1.97849315,  0.8889869 ],
       [-1.12231123, -1.55672899],
       [ 1.10639192, -1.21145146],
       [ 0.42809096, -0.46335012],
       [-1.60681191, -1.55672899],
       [ 1.00949178,  1.75218074],
       [-0.54091041,  2.29887018],
       [-0.25021   , -0.14684571],
       [-0.44401027,  2.27009705],
       [-0.73471068,  1.32058382],
       [-1.02541109, -1.12513207],
       [-0.83161082, -0.77985453],
       [-0.05640972, -0.37703074],
       [ 2.17229342,  1.0903988 ],
       [-0.15330986, -0.46335012],
       [-1.21921136,  0.57248249],
       [-0.83161082, -0.66476202],
       [ 2.17229342, -0.69353515],
       [-1.3161115 ,  0.39984372],
       [ 0.71879137,  1.75218074],
       [ 1.00949178,  1.95359264],
       [ 1.68779274,  1.72340761],
       [-0.15330986, -0.57844264],
       [ 0.23429069,  0.22720495],
       [ 0.13739055, -0.31948448],
       [-0.63781054,  0.11211244],
       [ 1.39709233,  0.57248249],
       [-0.25021   , -0.34825761],
       [-1.70371205,  0.34229746],
       [ 1.88159301, -0.29071136],
       [ 0.04049041, -0.57844264],
       [-0.83161082,  2.24132392],
       [ 1.00949178, -1.01003956],
       [ 0.42809096,  0.28475121],
       [-0.25021   , -0.29071136],
       [-0.34711013,  1.29181069],
       [ 1.10639192,  0.51493623],
       [-0.05640972,  0.11211244],
       [ 0.23429069, -0.37703074],
       [ 0.13739055,  0.25597808],
       [-0.73471068,  1.86727326],
       [-0.15330986,  0.83144064],
       [ 0.42809096,  0.14088557],
       [-0.15330986, -0.29071136],
       [-1.70371205, -0.60721576],
       [-0.25021   , -0.75108141],
       [-1.41301164,  0.34229746],
       [-0.25021   , -1.29777084],
       [ 1.00949178, -0.83740079],
       [ 1.20329206, -0.75108141],
       [ 0.33119082,  0.05456618],
       [ 0.04049041, -0.57844264],
       [-0.54091041,  1.86727326],
       [ 0.91259164,  1.23426444],
       [-0.34711013, -1.29777084],
       [ 0.81569151, -1.38409022],
       [ 2.07539329, -1.18267833],
       [ 1.49399247, -1.03881269],
       [-1.50991177,  0.31352434],
       [-0.44401027, -0.54966951],
       [ 1.10639192,  0.45738998],
       [ 0.5249911 ,  1.20549131],
       [ 0.33119082, -0.29071136],
       [-0.25021   , -1.3553171 ],
       [-1.3161115 , -1.3553171 ],
       [ 0.13739055,  1.03285254],
       [ 0.91259164, -1.3553171 ],
       [-0.25021   , -0.434577  ],
       [-1.89751232, -0.75108141],
       [-1.89751232,  0.34229746],
       [ 0.33119082, -0.52089638],
       [ 2.17229342, -0.80862766],
       [-0.05640972,  0.65880187],
       [-1.02541109, -0.37703074],
       [ 0.71879137, -1.38409022],
       [-0.73471068, -1.52795587],
       [-1.89751232,  0.45738998],
       [ 1.10639192,  0.11211244],
       [-1.41301164, -1.44163648],
       [ 0.23429069, -0.14684571],
       [ 0.81569151,  0.25597808],
       [ 0.42809096, -0.46335012],
       [-0.05640972,  0.28475121],
       [-0.25021   ,  1.0903988 ],
       [ 0.23429069,  1.06162567],
       [-1.12231123, -1.52795587],
       [-0.63781054, -0.11807259],
       [ 0.33119082,  0.4861631 ],
       [ 0.33119082,  0.28475121],
       [ 0.91259164,  2.12623141],
       [ 0.04049041, -0.26193823],
       [-1.12231123, -0.52089638],
       [-1.12231123, -1.58550212],
       [ 0.04049041,  1.20549131],
       [-0.63781054,  1.37813008],
       [-0.25021   , -0.57844264],
       [-0.92851095, -0.434577  ],
       [-0.73471068,  0.54370936],
       [ 2.07539329,  0.16965869],
       [ 0.13739055,  1.83850013],
       [-0.54091041,  1.34935695],
       [ 1.30019219,  1.83850013],
       [ 0.33119082, -0.20439197],
       [-1.80061218,  0.16965869],
       [-1.60681191, -0.06052633],
       [-0.92851095,  0.39984372],
       [ 0.62189123, -0.89494705],
       [-0.05640972,  0.22720495],
       [ 1.00949178,  2.03991202],
       [ 0.33119082,  0.02579305],
       [-1.41301164, -0.20439197],
       [-1.3161115 ,  0.54370936],
       [ 1.00949178, -1.06758582],
       [-1.3161115 , -1.24022458],
       [ 0.23429069, -0.31948448],
       [ 0.81569151, -1.09635894],
       [ 1.20329206, -1.44163648],
       [ 1.10639192, -0.14684571],
       [-0.54091041, -1.49918274],
       [ 2.17229342, -0.80862766],
       [ 0.33119082, -0.52089638],
       [-0.83161082,  0.37107059],
       [ 1.10639192, -0.89494705],
       [-0.83161082, -1.21145146],
       [ 0.81569151, -1.21145146],
       [ 1.39709233, -1.41286335],
       [ 1.68779274, -0.89494705],
       [ 1.10639192,  2.03991202],
       [-1.02541109,  1.92481951],
       [ 1.49399247,  0.34229746],
       [-1.80061218,  0.42861685],
       [-0.25021   , -0.57844264],
       [-1.12231123, -1.1539052 ],
       [-0.05640972, -0.2331651 ],
       [ 0.04049041, -0.14684571],
       [ 0.13739055,  0.19843182],
       [-1.89751232, -0.06052633],
       [ 1.78469288,  0.97530628],
       [-0.54091041, -1.49918274],
       [-1.50991177, -1.24022458],
       [ 0.62189123,  1.98236577],
       [-0.63781054, -1.03881269],
       [-1.21921136, -1.38409022],
       [ 1.88159301, -1.06758582],
       [-0.25021   , -0.89494705],
       [-0.92851095, -0.75108141],
       [-1.41301164, -0.11807259],
       [ 0.23429069,  0.14088557],
       [ 0.42809096,  0.25597808],
       [ 0.91259164,  1.00407941],
       [-1.02541109, -0.34825761],
       [ 1.49399247,  2.09745828],
       [ 1.5908926 , -0.00298007],
       [ 0.91259164, -1.29777084],
       [ 2.17229342,  0.37107059],
       [-1.02541109, -1.52795587],
       [ 0.33119082,  0.05456618],
       [-0.44401027,  1.23426444],
       [-1.21921136, -1.06758582],
       [ 0.81569151, -0.83740079],
       [-0.25021   ,  0.60125562],
       [ 0.81569151, -0.31948448],
       [-0.25021   , -0.49212325],
       [ 1.5908926 , -1.26899771],
       [ 1.39709233,  1.95359264],
       [-0.83161082,  0.28475121],
       [ 0.13739055, -0.26193823],
       [ 0.42809096,  1.0903988 ]])

In [16]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled,columns = X_test.columns)

In [17]:
X_train_scaled

          Age  EstimatedSalary
0    1.106392        -0.981266
1    0.912592        -1.441636
2    1.203292        -0.981266
3   -0.250210         0.198432
4   -0.637811        -0.348258
..        ...              ...
275  1.590893        -1.268998
276  1.397092         1.953593
277 -0.831611         0.284751
278  0.137391        -0.261938
279  0.428091         1.090399

[280 rows x 2 columns]

In [18]:
X_test_scaled

          Age  EstimatedSalary
0    0.428091        -0.146846
1   -0.056410         0.025793
2    0.428091         0.572482
3    0.912592        -0.664762
4   -1.413012        -0.635989
..        ...              ...
115  0.718791        -1.268998
116 -0.056410        -0.492123
117  2.172293         0.917760
118 -0.540910         1.349357
119  0.428091         0.284751

[120 rows x 2 columns]

In [19]:
X_train.describe()

              Age  EstimatedSalary
count  280.000000       280.000000
mean    37.582143     70103.571429
std     10.338381     34816.878679
min     18.000000     15000.000000
25%     30.000000     43000.000000
50%     37.000000     70000.000000
75%     46.000000     88250.000000
max     60.000000    150000.000000

In [21]:
np.round(X_train.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.6          70103.6
std     10.3          34816.9
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70000.0
75%     46.0          88250.0
max     60.0         150000.0

In [22]:
X_train.describe()

              Age  EstimatedSalary
count  280.000000       280.000000
mean    37.582143     70103.571429
std     10.338381     34816.878679
min     18.000000     15000.000000
25%     30.000000     43000.000000
50%     37.000000     70000.000000
75%     46.000000     88250.000000
max     60.000000    150000.000000

## Why Scaling is Important?

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [26]:
lr.fit(X_train, y_train)
lr_scaled.fit(X_train_scaled, y_train)

LogisticRegression()

In [32]:
y_pred = lr.predict(X_test)
y_pred_scaled = lr_scaled.predict(X_test_scaled)

In [33]:
## Checking the accuracy
from sklearn.metrics import accuracy_score
print("Actual: ",accuracy_score(y_test, y_pred))
print("Scaled: ",accuracy_score(y_test,y_pred_scaled))

Actual:  0.6916666666666667
Scaled:  0.875

In [34]:
y_test.shape

(120,)

In [35]:
y_pred.shape

(120,)

In [36]:
## Now we'll using the Decision Tree Classifier to check there would be any effect of Scaling the values as we know
## there would be no use of it , so let's check it

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
dt = DecisionTreeClassifier()
dt_scaled = DecisionTreeClassifier()

In [39]:
dt.fit(X_train, y_train)
dt_scaled.fit(X_train_scaled, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = dt.predict(X_test)
y_pred_scaled = dt_scaled.predict(X_test_scaled)

In [42]:
## Checking the accuracy score
print("Actual: ",accuracy_score(y_pred,y_test))
print("Scale: ",accuracy_score(y_pred_scaled,y_test))

Actual:  0.875
Scale:  0.875